### ISSUE TITLE
virtualenv and numpy+mkl

### ISSUE THREAD

**Issue by ShuguangSun** [winpython/winpython#1026]
I'm using winpython with numpy+mkl, and want to use virtualenv for development. However I don't know how to install the numpy+mkl coming with winpython to the virtualenv?

Is it the only way to do it by downloading numpy+mkl from ldf unoffical libs?

**Comment by firai** [comment]
Since WinPython uses [Gohlke (UCI LFD) wheels](https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy) as you mentioned, installing his wheels directly is the cleanest way. There may be some complicated workaround involving copying files and dist-info from `Lib\site-packages` from another installation, but ~~there are no guarantees that this would work~~ this will likely not function properly, and I don't think anyone can help you if things go wrong in this case.

**Comment by ShuguangSun** [comment]
Got it. Thanks.
