### ISSUE TITLE
all Nullsoft based exe launchers are broken for several releases now.. (controlpanel.py, qtpy)

### ISSUE THREAD

**Issue by ghost** [winpython/winpython#1117]
checked the ~30mb assets from https://github.com/winpython/winpython/releases/tag/5.0.20220918  
none of the base-folder exe seems to be working,  
except the three that are console-based (I.E. `WinPython Command Prompt.exe` for cmd, `WinPython Interpreter.exe` for python, and `WinPython Powershell Prompt.exe` for ps).  

I've `editbin.exe /NOLOGO "/SUBSYSTEM:CONSOLE" "WinPython Command Prompt.exe"` to make Windows assign a stdout pipe to the exe, and to try to see if there are some logs thrown..  ..nothing.  

I got the value of `ErrorLevel`,  
and it gives exit code of 9009,  
but [it seems](https://www.google.com/search?q=nullsoft+9009) not to be actually related to any error, but how (crappy) nsis is built..  

the batch-files under `scripts/` folder seemed to be helpful,  
but are also ending with an error,  
for example:

```cmd
C:\WPy64\scripts>register_python_for_all.bat
C:\WPy64\python-3.10.7.amd64
"C:\WPy64\python-3.10.7.amd64\python.exe" -c "import sys; print(sys.maxsize > 2**32)"  *  C:\WPy64\python-3.10.7.amd64
"C:\WPy64\python-3.10.7.amd64\python.exe" -c "import sys; print('%d.%d' % (sys.version_info.major, sys.version_info.minor))"  *  C:\WPy64\python-3.10.7.amd64
"C:\WPy64\python-3.10.7.amd64\python.exe" -c "import sys; print('%d.%d.%d' % (sys.version_info.major, sys.version_info.minor,sys.version_info.micro))"  *  C:\WPy64\python-3.10.7.amd64
Traceback (most recent call last):
  File "C:\WPy64\python-3.10.7.amd64\Scripts\register_python", line 24, in <module>
    associate.register(args.target, current=not args.all)
  File "C:\WPy64\python-3.10.7.amd64\lib\site-packages\winpython\associate.py", line 282, in register
    for path, desc, fname in _get_shortcut_data(
  File "C:\WPy64\python-3.10.7.amd64\lib\site-packages\winpython\associate.py", line 42, in _get_shortcut_data
    wpgroup = utils.create_winpython_start_menu_folder(
  File "C:\WPy64\python-3.10.7.amd64\lib\site-packages\winpython\utils.py", line 222, in create_winpython_start_menu_folder
    path = get_winpython_start_menu_folder(current=current)
  File "C:\WPy64\python-3.10.7.amd64\lib\site-packages\winpython\utils.py", line 209, in get_winpython_start_menu_folder
    folder = get_special_folder_path(
  File "C:\WPy64\python-3.10.7.amd64\lib\site-packages\winpython\utils.py", line 184, in get_special_folder_path
    from win32com.shell import shell, shellcon
ModuleNotFoundError: No module named 'win32com'

C:\WPy64\python-3.10.7.amd64\Scripts>
```

I've also sxstrace it, but it doesn't seems to be manifest related,  

and the only thing I can tell (using nirsoft fileactivity)  
is that executing the exe launches a sub process of `C:\Windows\SysWOW64\wscript.exe` which launches  
`C:\WPY64\SCRIPTS\NOSHELL.VBS` and `C:\Windows\SysWOW64\wshom.ocx`  
and then (by this order)  
`C:\WPy64\scripts\wpcp.bat`  
`C:\WPy64\scripts\env_for_icons.bat`  
`C:\WPy64\scripts\env.bat`  
`C:\Windows\SysWOW64\cscript.exe`  
`C:\WPY64\SCRIPTS\WINPYTHONINI.VBS`  
`C:\Windows\SysWOW64\ScrRun.dll`  
`C:\WPy64\settings\winpython.ini`  
`C:\WPy64\python-3.10.7.amd64\python.exe`  
various `C:\WPy64\python-3.10.7.amd64\lib\__pycache__`  
`C:\WPy64\python-3.10.7.amd64\lib\runpy.py`  
`C:\WPy64\python-3.10.7.amd64\lib\site-packages\winpython\controlpanel.py`  
`C:\WPy64\python-3.10.7.amd64\lib\site-packages\winpython\_vendor\qtpy\__init__.py`  

but it ends there.  

trying to launch `wpcp.bat` gives this output:

```cmd
C:\WPy64\scripts>wpcp.bat
Traceback (most recent call last):
  File "C:\WPy64\python-3.10.7.amd64\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\WPy64\python-3.10.7.amd64\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\WPy64\python-3.10.7.amd64\lib\site-packages\winpython\controlpanel.py", line 20, in <module>
    from winpython._vendor.qtpy.QtWidgets import (
  File "C:\WPy64\python-3.10.7.amd64\lib\site-packages\winpython\_vendor\qtpy\__init__.py", line 57, in <module>
    from packaging.version import parse
ModuleNotFoundError: No module named 'packaging'
```

with exit code `1`.  

<hr/>

might be the possible cause for the launcher to break..  

let me know if I can provide more information..

note:  
it would be a lot quicker to debug if the launcher wasn't that cursed nsis to wscript to bat chain,  
pretty much every programing language that compiles a exe (c++, vb.net, c#..) can create a tiny console (no forms) program that can use shellexecute with sw_hide to launch a batch file or whatever argument it gets, and by setting the project to use Windows GUI subsystem (..or post-build using `editbin.exe "/SUBSYSTEM:WINDOWS"`) you can avoid that console window..

**Comment by firai** [comment]
Are you referring to the "dot" release? The dot release only contains a barebones Python environment ([WinPythondot-32bit-3.10.5.0.md](https://github.com/winpython/winpython/blob/master/changelogs/WinPythondot-32bit-3.10.5.0.md)) that's similar to what you get (if not even more barebones) from just downloading the Python binary from [python.org](http://www.python.org), and it does not contain the packages required to run the programs that the shortcuts refer to. You can refer to the descriptions and package lists for previous official releases on the [homepage](https://winpython.github.io/) to get an idea of the difference. For example, `wpcp.bat` (WinPython Control Panel) that you referred to requires one of the Qt distributions to be installed (see the Requirements section in [README.rst](https://github.com/winpython/winpython/blob/master/README.rst)). Similarly, Spyder, Jupyter and other programs aren't included in the dot release. You can see that from the error logs you posted, which show Python `ModuleNotFoundError` errors saying that it can't find the packages referred to in the scripts rather than NSIS internal errors. It is probably confusing that most of the shortcuts are included in the dot release at all.

I just tried the full release (i.e. the 787 MB one without "dot" in its name), and the shortcuts work for me. If you want to use the programs that the shortcuts refer to, can you try downloading the full release?
