### ISSUE TITLE
Qt plot window problems in Spyder's classic Python console

### ISSUE THREAD

**Issue by jondo** [winpython/winpython#191]
With `WinPython-64bit-3.4.3.6.exe`, when I am using Spyder to run the minimal script
```python
import matplotlib.pyplot as plt
plt.scatter([0], [0])
```
in a Python console, the Qt window only opens the first time. When I close it and run the script again, the Qt window only opens after pressing ctrl+c in the console.

`WinPython-32bit-3.4.3.6.exe` has the same problem.

With `WinPython-64bit-3.4.3.6Qt5.exe`, the plot window even freezes and crashes Python.exe when it's opened the first time, without displaying anything.

With `WinPython-64bit-3.4.3.5.exe`, the Qt window reopens as expected everytime I close it and rerun the script.

**Comment by stonebig** [comment]
Strange: trying your first example, I get no issue 
![w3 4 3 6qt4_test1](https://cloud.githubusercontent.com/assets/4312421/10849107/69722858-7f1f-11e5-9c28-d939ff07a743.GIF)

**Comment by stonebig** [comment]
trying on `WinPython-64bit-3.4.3.6Qt5.exe` on my pc , I get no issue either:
![w3 4 3 6qt5_test1](https://cloud.githubusercontent.com/assets/4312421/10849237/04031526-7f20-11e5-8ca7-6fb2014b8a4a.GIF)

**Comment by stonebig** [comment]
executing manually on the pure classic python console of spyder , I get your problem.

**Comment by stonebig** [comment]
spyder doesn't crash, so I don't have a `spyder_crash.log`.
This example works (doesn't die):
````
import matplotlib.pyplot as plt
plt.scatter([0, 1 ], [0 , 1 ])
plt.show()
plt.close()
````
and if you launch it after a "freezing matplotlib tcl/tk" window, it closes it

**Comment by stonebig** [comment]
I know there is a weakness at first starting of spyder on a very slow or busy pc:
- that may be this (time-out extension) fix: https://github.com/spyder-ide/spyder/commit/3f72574e8226058937b17ffaea656a4921ffecf0
- that solves itself when launching it twice.

But yours is a bit strange:
- it doesn't seem 32/64 bit related, or Qt4/Qt5, or tcl/tk
- it doens't work also on Winpython 2.7.10.3
- it works on a IDLE console if we do:
````
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
plt.scatter([0, 1 ], [0 , 1 ])
plt.show()
````

So it may point to a spyder 3.0 or matplotlib 1.5rc3 weakness

Downgrading to Matplotlib 1.4.3 to solve the issue

**Comment by stonebig** [comment]
this will show your graph:
````
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
plt.scatter([0, 1 ], [0 , 1 ])
plt.show()
plt.pause(5)
plt.close()
````

the "pause" idea comes from this closed issue https://github.com/spyder-ide/spyder/issues/1831

**Comment by jondo** [comment]
Thank you for confirming my observations, and for forwarding this to Spyder. Sorry for not being clear enough that I'm speaking of Spyder's "classic" Python console.

I will stay with WinPython-3.4.3.5 for now.

**Comment by jondo** [comment]
With your suggestion to use "a Ipython qtconsole of Spyder", do you mean to change Spyder -> Tools -> Preferences -> IPython console -> Graphics -> Backend ?

I have changed this to `Automatic`. Now my original example works in both the Qt4 and Qt5 versions of WinPython-64bit-3.4.3.6!

I was not aware about this method to get interactive plot windows. Maybe I won't use Spyder's "classic" Python console any more now :-)

**Comment by hiccup7** [comment]
Another problem I find with the classic Python console in 64-bit WinPython 3.4.3.6 is that plotting with matplotlib (in my code or from the variable explorer) kills the ability to interact with the console afterward.  I have to close and console and open another one.  Since I prefer the classic Python console for many reasons, this makes WinPython 3.4.3.6 unusable for me.  I am staying on WinPython 3.4.3.5 for now.

If the intention is that WinPython 3.4.3.6Qt5 has bleeding-edge and new-feature library versions, and WinPython 3.4.3.6 is stable with bug fixes, then WinPython release 2015-08 could fix this bug by including a version with Python 3.4, Qt4 and _released_ versions of Spyder and matplotlib.

I would really like to have the current bug fixes for NumPy and SciPy with a working classic Python console.  Can this be done by uninstalling these modules from WinPython 3.4.3.5 and installing the updates from http://www.lfd.uci.edu/~gohlke/pythonlibs/ ?

**Comment by stonebig** [comment]
hi @hiccup7 , 

You can uninstall your current numpy and scipy, and install other ones from ~cgohlke using the 'WinPython Control Panel'.

Winpython tries to bring the same level of packages for all branches (2.7 and 3.4, 32bit and 64 bit, Qt4 and Qt5):
- it's easier for user to switch between branches,
- it's easier to maintain also: one set of bugs.

Winpython 201506 was pushed for "back to school" season and before the big (unavoidable) changes, so with statistically less chances of bugs for a program/working habit that was ok in June 2015.

.

**Comment by hiccup7** [comment]
@stonebig Thanks.  Updating NumPy and SciPy in WinPython 3.4.3.5 worked well.

Spyder has had two v2.3.X releases since WinPython 3.4.3.5 came out:
https://github.com/spyder-ide/spyder/releases

Can I upgrade Spyder in WinPython 3.4.3.5 using the 'WinPython Control Panel'?  I am not clear on whether spyder.exe in WinPython's scripts folder will automatically update.

**Comment by stonebig** [comment]
Yes you can:
-  1-download the new spyder you prefer (personnaly, I would strongly suggest the wheel from Christoph Gohlke: http://www.lfd.uci.edu/~gohlke/pythonlibs/#spyder)
-  2 - start 'WinPython Control Panel'
-  3 - remove existing spyder3 package,
-  4 - install the just download Spyder 

Let us know if you have still your problem or not after that

**Comment by hiccup7** [comment]
@stonebig I used the Gohlke wheel as you suggested, and it worked great.  Thanks for your suggestion!

**Comment by stonebig** [comment]
Happy you're happy. By the way, are you still playing also with Julia ? I didn't have time to look at them since 9 month

**Comment by hiccup7** [comment]
I haven't been using Julia since I did the deep comparison against Python.  Among free scientific languages, I found that Python execution is faster because:
1. WinPython has MKL while there is no free Julia download with MKL
2. Julia is only tested with OpenBLAS, which doesn't support dynamic number of threads like MKL
3. Julia is based on LLVM v3.3, so user-written code doesn't use SIMD instructions and multithreading.  Python's Numexpr, Numba (based on LLVM v3.6) and Cython packages provide much better speed.

Julia has a beautiful syntax, so I hope to move to it when these issues are resolved.

**Comment by stonebig** [comment]
ok, thanks a lot for this update. Julia came on my mind again because I have no Pulp for Python3.5 yet, and JuMP seems the only alternative.

**Comment by hiccup7** [comment]
Is my understanding about upgrading these packages in WinPython 3.4.3.5 correct?
numexpr 2.4.3 → 2.4.6 by using Gohlke's wheel
numba 0.20.0 → 0.22.1 by using Gohlke's wheels for numba and llvmite‑0.8.0 and installing the Universal C Runtime

**Comment by stonebig** [comment]
numexpr is natural refresh (for all versions)

numba+llvmlite starting 0.21 require the 'Universal C Runtime'.

==> It was not a 'problem' to upgrade numba+llvmlite for WinPython 3.5, as Python 3.5 itself requires it.

**Comment by stonebig** [comment]
The Spyder-ide decided to just remove this option.

**Comment by jondo** [comment]
Which option? To open plot windows from the classic Python console? What happens instead?

**Comment by stonebig** [comment]
maybe my wording is not perfect, see [there](https://github.com/spyder-ide/spyder/issues/2788#issuecomment-158691143)

**Comment by jondo** [comment]
I don't understand the following:
https://github.com/spyder-ide/spyder/issues/2788 deals with (removing) the Tk backend, but this issue is about the Qt backend. Notice the plot window icon in https://github.com/winpython/winpython/issues/191#issuecomment-152552675, which is a sinus function, not Tk's blue feather.

**Comment by stonebig** [comment]
ah. So Maybe in next Spyder-ide beta, coming this week-end, we may have a good surprise.

**Comment by clovis46** [comment]
Hello, I have a problem also with WinPython-32bit-3.4.3.7Qt5. 
I cannot display a simple plot with spyder :

`import matplotlib.pyplot as plt
plt.scatter([0], [0])
plt.show()`
 
The Fig1 appears but it is frozen and nothing on it

Clovis
