### ISSUE TITLE
How to update pylint?

### ISSUE THREAD

**Issue by hiccup7** [winpython/winpython#212]
I am using WinPython v3.4.3.5 presently because it has a stable combination of Python, NumPy, Qt matplotlib and Spyder.  It includes pylint v1.4.3, astroid v1.3.6 and logilab_common v1.0.2.  My Python code is working, and without errors or warnings thrown by pylint.

I would like to update my current WinPython v3.4.3.5 to pylint v1.4.5 for bug fixes, and I would like to create a second WinPython v3.4.3.5 environment with pylint v1.5.1 for testing.  I would like advice on which wheel files to install with the WinPython Control Panel.

Here is the change log for pylint v1.4.5:
https://bitbucket.org/logilab/pylint/src/66b73ed633c2254e8ff16ddcdf70589b174bcf92/ChangeLog?at=pylint-1.4.5

This commit shows that pylint v1.4.5 is restricted to use only astroid v1.3.8:
https://bitbucket.org/logilab/pylint/commits/66b73ed633c2254e8ff16ddcdf70589b174bcf92?at=pylint-1.4.5

With pylint v1.4.5, I assume that the latest logilab-common version is preferred.  Here are the specific packages:
https://pypi.python.org/pypi/pylint/1.4.5
https://pypi.python.org/pypi/astroid/1.3.8
https://pypi.python.org/pypi/logilab-common/1.1.0

Questions:
The page for pylint v1.4.5 is showing a build failure.  Is it dangerous to use this?
The page for logilab-common v1.1.0 does not include a wheel file.  Should I avoid updating this?

Here are sources I found for the latest versions of the logilab packages:
https://pypi.python.org/pypi/pylint/1.5.1
http://www.lfd.uci.edu/~gohlke/pythonlibs/
https://pypi.python.org/pypi/astroid/1.4.1

Questions:
The pypi page for pylint v1.5.1 is showing a build failure.  Is it dangerous to use this?
gohlke and pypi wheels for pylint are the same size, but the files don't match.  Which is preferred?
Do I understand correctly that pylint v1.5.x doesn't require the logilab-common package?
If true, can I uninstall the logilab-common package from WinPython v3.4.3.5 to avoid confusion?

Thanks in advance.

**Comment by stonebig** [comment]
hi @hiccup7 

`The pypi page for pylint v1.5.1 is showing a build failure. Is it dangerous to use this?`
No, it just shows that current tree on github fails.

`gohlke and pypi wheels for pylint are the same size, but the files don't match. Which is preferred?`
Difference between Christoph Gohlke wheels and pip wheels can be:
- the <NewLine> definition of the computer generating a wheel: 
   - Windows uses CRLF (\r\n),
   - Unix uses LF (\n)
- sometimes a bugfix that Christoph is adding,
- maybe other reasons.

Because of bug fixes (or bug control) that Christoph is adding, I may prefer Christoph when I know the package is problematic.

`Do I understand correctly that pylint v1.5.x doesn't require the logilab-common package?`
Indeed, and the pip install requirements detected it automatically (as it was well specified by the maintainer)

**Comment by stonebig** [comment]
for the pylint thing, I would follow Christoph Gohlke, and so, use something like:
- pylint 1.5.1.
- wrapt 1.10.5
- astroid 1.4.1
- lazy_object_proxy 1.2.1

I kept an older version of astroid than Christoph previously, because of a problem I don't remember.
So I won't suggest you any version between astroid 1.3.7 and 1.4.1 as a good idea.

**Comment by hiccup7** [comment]
Do you mean lazy_object_proxy 1.2.1 from https://pypi.python.org/pypi/lazy-object-proxy/1.2.1
and the other three packages from gohlke?

I don't see wrapt and lazy_object_proxy in WinPython v3.4.3.5.  Why are they needed for pylint?

**Comment by stonebig** [comment]
Not sure it's via pylint or via astroid, but the droping of logilab-common was in favor of other smaller packages.

see https://bitbucket.org/logilab/astroid/issues/170/use-functoolswraps-or-wrapt-for-decorators for wrapt

**Comment by stonebig** [comment]
Christoph Gohlke did some lazy work for you: http://www.lfd.uci.edu/~gohlke/pythonlibs/#lazy_object_proxy

**Comment by hiccup7** [comment]
Thanks Christoph!

I updated my WinPython 3.4.3.5 environment with the latest four pylint-related packages from Christoph's site that stonebig suggested, and it is now working well.

I saw this problem initially:
http://stackoverflow.com/questions/20553551/how-do-i-get-pylint-to-recognize-numpy-members

I used the solution of adding the following to my pylintrc file:
[TYPECHECK]
ignored-modules = numpy

Here is documentation of pylintrc options:
https://bitbucket.org/logilab/pylint/src/5ad1348455fe4758b0dcab4051e5f1c33d54dd66/pylintrc?at=default

@stonebig  - thanks for your help.  I am a happy Python user... closed issue.
