### ISSUE TITLE
Error Launching Jupyter Notebook - WinPython 3.5.1.3

### ISSUE THREAD

**Issue by jackjameshoward** [winpython/winpython#314]
I installed the latest winpython version 3.5.1.3 and launched notebook using the executable and I get this error.

> 'K:\Program' is not recognized as an internal or external command,
> operable program or batch file.
> The syntax of the command is incorrect.
> K:\Program Files\Python 3.5\scripts>

Any ideas?

**Comment by stonebig** [comment]
it abiously doesn't like the "spaces" in your directory path

**Comment by jackjameshoward** [comment]
Its just strange that I haven't had this problem with previous distribution of WInpython in the same directory.
What is it that causes this problem?

**Comment by stonebig** [comment]
until this release, the code behind the icons was coded in NSIS script, a technical debt and code you can't tweak on your installation.
Now the icon just call a .bat script, here "scripts\ipython_notebook.bat".

Fact is I don't understand why I can't make it work but, the simple "scripts\cmd.bat" resists working with a space in the path, since you make the notice.

==> help me fix "scripts\cmd.bat" and it should work again

**Comment by stonebig** [comment]
ok. try this:
change scripts\cmd.bat:
````
call %~dp0env_for_icons.bat
````

per
````
call "%~dp0env_for_icons.bat"
````

and in scripts\env_for_icons.bat:
````
call %~dp0env.bat
````
per 
````
call "%~dp0env.bat"
````

**Comment by stonebig** [comment]
you may confirm it works with this simple fixes

**Comment by jackjameshoward** [comment]
@stonebig Thank you very much. 
That works
