### ISSUE TITLE
Default find in files pane broken in Spyder in WinPython (v3.5)

### ISSUE THREAD

**Issue by DStauffman** [winpython/winpython#355]
When I install a clean version of WinPython v3.5.1.3 on Windows 10, then within Spyder, the "Find in Files" pane doesn't work.  It gives a an error of "Search cancelled (invalid regular expression)".  Looking into the very lengthy expression in the "Include:" field, shows that there are invalid regular expression characters such as \u or \p.  I don't know where these all come from, but it looks like a lot of them have stranded slashes that either shouldn't be there, or should be slash dots instead.

Some examples:
|\utodelegate$| ...  |\pache.conf$|\pache2.conf$|   ...   |\gvimrc$|\imrc$|\vimrc$|  

Changing this include field to the much simpler version below makes everything work as expected.
|\.py$|\.pyw$|\.pyx$

**Comment by hiccup7** [comment]
Your issue may be with Spyder 3.0.0.dev0 instead of WinPython.  My suggestion is to try WinPython 3.5.2.1rc, which includes Spyder 3.0.0b4.  This WinPython build is documented at https://github.com/winpython/winpython/issues/309
The downloads are available at https://sourceforge.net/projects/winpython/files/WinPython_3.5/3.5.2.1/betas/

If you find an issue with Spyder 3.0.0b4, you can report it to the Spyder team at https://github.com/spyder-ide/spyder

Since WinPython 3.5.2.1rc uses Qt4, you can replace Spyder 3.0.0b4 with 2.3.9 from here http://www.lfd.uci.edu/~gohlke/pythonlibs/#spyder
using the WinPython Control Panel.  It would be helpful to the Spyder team to know if your issue is a regression relative to 2.3.9.

**Comment by stonebig** [comment]
could it be related to  https://github.com/spyder-ide/spyder/pull/3295 , merged 3 days ago in spyder master ?

**Comment by DStauffman** [comment]
I did just confirm with WinPython3.5.2.1rc2 that this is no longer present.  It does look like exactly the issue #3295.  It looks like the extra test case in test_findinfiles.py is perfect for preventing it again.  I believe we can close this.  Thanks!
