### ISSUE TITLE
Spyder (Python 2.7) console freezes plotting with matplotlib

### ISSUE THREAD

**Issue by fromagek** [winpython/winpython#359]
Using Winpython 2.7.10.3 the spyder console freezes after displaying a plot with matplotlib.
With Winpython 2.7.10.2 I cannot observe this behavior.

minimal example:
```python
from matplotlib import pyplot as plt
import numpy as np

x=np.linspace(0,2*np.pi,1000)
y=np.sin(x)
plt.plot(x,y)
```

**Comment by stonebig** [comment]
Hi @fromagek 

I think it is the same issue as https://github.com/winpython/winpython/issues/191

Suggestions:
- execute the script in a "dedicate Python console" (not the default created per spyder)
- or use Spyder "Qtconsole" rather than the "classic" not working well standard console
- or do that in IDLEX

**Comment by Travis-Barton** [comment]
I am still having this issue. I cannot run a simple plot in the editor.  Has this been resolved?

**Comment by derekeden** [comment]
> I am still having this issue. I cannot run a simple plot in the editor. Has this been resolved?

Don't think so, I had to switch IDEs because I could not make an interactive plot. I tried every solution I could find on github, stack, etc. Even inline plotting or in the plot windows freeze. Every backend.
