### ISSUE TITLE
WinPython Control Panel won't launch

### ISSUE THREAD

**Issue by MichaelClerx** [winpython/winpython#397]
Hi all,

I just downloaded the latest WinPython2.7.12.3 which seems to only be available as a "Zero" option. I'd like to add some packages using the control panel, but that won't start! When I run the exe nothing happens. Running it from a Command Prompt the same happens, and no error message is generated.

Any ideas what could be causing this?

Best,
  Michael

**Comment by stonebig** [comment]
"Zero" means there is nearly zeropackage:
- there is no PyQt package,
-  WinPythonControlPanel requires PyQt (4 or 5, and so can't launch.

To add PyQt4 on your Zero WinPython, you may try this:
- download a PyQt4 binary wheel (from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4) in a local directory of yours (let says "d:\toto"):
 - PyQt4-4.11.4-cp27-none-win32.whl if you are using Python 32 bit
 - PyQt4-4.11.4-cp27-none-win_amd64.whl if you are using Python 64bit
- launch "WinPython Command Prompt.exe"
- type "wppm -i  d:\toto\PyQt4-4.11.4-cp27-none-win32.whl" if you are 32 bit
- otherwise "wppm -i  d:\toto\PyQt4-4.11.4-cp27-none-win_amd64.whl" if you are 64 bit

**Comment by MichaelClerx** [comment]
Thanks for clarifying!

But I think I'll just stick with 2.7.10.3 then :-)
Not having to install extra packages is one of my favourite things about WinPython!

**Comment by stonebig** [comment]
May Iask why are you sticking with 2.7 ?

**Comment by MichaelClerx** [comment]
Of course!
I maintain a Python-based toolkit that was started as a 2.7 project since that was the default available on my system at the time. At some time in the future I want to switch to Python3, but that means that (1) my users will have to re-install instead of just being able to upgrade, (2) I lose a lot of time rewriting and debugging something that already works fine. I'm not against Python3, but it doesn't have any features I lack in 2.7, so it simply hasn't been worth the effort.

**Comment by stonebig** [comment]
ok, I understand. thanks for sharing.

**Comment by MichaelClerx** [comment]
(It also depends on things like Canopy, which os/x users seem to enjoy)

**Comment by stonebig** [comment]
Python 2 is not bad, when you never suffered of code-page and technical debt in your life.

**Comment by stonebig** [comment]
as a side note: 

To add PyQt4 then spyder  on your Zero WinPython, you may try this:
- download a PyQt4 binary wheel (from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4) in a local directory of yours (let says "d:\toto"):
 - PyQt4-4.11.4-cp27-none-win32.whl if you are using Python 32 bit
 - PyQt4-4.11.4-cp27-none-win_amd64.whl if you are using Python 64bit
- launch "WinPython Command Prompt.exe"
- type "wppm -i  d:\toto\PyQt4-4.11.4-cp27-none-win32.whl" if you are 32 bit
- otherwise "wppm -i  d:\toto\PyQt4-4.11.4-cp27-none-win_amd64.whl" if you are 64 bit 
- then to add Spyder should be just "pip install spyder"

**Comment by maphew** [comment]
So for clarity and benefit of future searchers (a lot of links to this issue): the latest version of WinPython 2.7 that includes a WP Control Panel and Spyder that works out of the box is https://sourceforge.net/projects/winpython/files/WinPython_2.7/2.7.10.3/

Yes?

**Comment by MichaelClerx** [comment]
Yup!

**Comment by aghasemi** [comment]
Hi,
I would like to add a note. Merely downloading and installing PyQt4 as mentioned above di not solve the problem for me. Here is what I had to do:

- Download scandir, PyQt4, and spyder from (this wonderful  link)[http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4]

- Install them in order, at least scandir before spyder

- Use `pip install`. wppm didn't work me

**Comment by tlawork** [comment]
I can not understand why a prestigious distribution like WinPython would limit python 2 distributions so they don't work out of the box.  I wasted a lot of time on this.  Like others I am not against python 3 but I have a system which relies on python 2.7.6.  Sorry for the negativity but it seems arrogant to limit distributions to help people make the move to python 3. Not everyone can make that leap yet.

**Comment by stonebig** [comment]
hi @tlawork.

Doing a full WinPython-2.7 was taking time and energy needed to keep-up with ecosystem changes,

Even in open-source projects, the project dies if:
- it can't keep up with evolutions (Qt5.8, Jupyterlab, Feather, Arrow, ... pypy ...),
- it doesn't clean-up its technical debt, to allow/facilitate evolutions,
- it doesn't focus on a limited set, as you can't do everything and be competitive/worth-it (a Heisenberg principle of Software).

**Comment by stonebig** [comment]
and my secret hope was that standard Python continue to improve, so that upgrading to a full Winpython a WinPythonZero would become easy. Sorry, it didn't happen yet.
