### ISSUE TITLE
IDLE highlighting themes are buggy / unusable

### ISSUE THREAD

**Issue by s-moffett** [winpython/winpython#460]
Windows 10, WinPython-64bit-3.5.2.3Zero

Changing the highlighting theme of an empty open file (in this case from classic to dark) will change the background and foreground colors, but as soon as the user types the background will reset to tan. This makes the dark theme unusable.

This is my first open source contribution, so I don't really know the procedure to handle this. If someone wants to help a newbie and point out where this code is, I'd love to write a patch.

![winpython_bug](https://cloud.githubusercontent.com/assets/25062471/21874475/128ffb90-d843-11e6-801d-87fd4468b2a9.PNG)

**Comment by stonebig** [comment]
Hello @s-moffett , welcome to github.

This may be a "IDLEX" problem, a project that is nearly dormant https://sourceforge.net/p/idlex/discussion/general/thread/5c09f981/

otherwise it's "IDLE" project.

In any case, WinPython project can't do  anything about it, except remove IDLEX. 
(pip uninstall IDLEX)

**Comment by s-moffett** [comment]
Okay, if I see some development from IDLEX I'll pass this on. Thanks for being so welcoming.
