### ISSUE TITLE
Qt Designer and other Qt exes missing

### ISSUE THREAD

**Issue by ngblume** [winpython/winpython#465]
Hello,

I'm getting started with Python and WinPython, so please excuse my question if I'm missing something..
I ran the WinPython-64bit-3.5.2.3Qt5.exe and got everything running smoothly, except, that there are no exe's from the Qt side of things in the folder WinPython was exported to.
I followed a tutorial at http://projects.skylogic.ca/blog/how-to-install-pyqt5-and-build-your-first-gui-in-python-3-4/ and it suggests the Qt Designer at "C:\Program Files\Python34\Lib\site-packages\PyQt5\designer.exe", which after changing the path accordingly, showed no designer.exe at all...
Furthermore in the directory WinPython was extracted to, there are no Qt *.Exe files, neither Qt Designer, nor Qt Assistant, and so on...
By caomparing to https://winpython.github.io/, every exe is there, except the Qt related exe's.

I'm sure, I'm missing something obvious here... Please help me see it....

Thanks!

Cheers
Niels Göran

**Comment by ngblume** [comment]
Just to be on the safe side:
I saw the issue "Qt Designer for Qt5 #431"....
I was confused since the https://winpython.github.io/ webpage still advertises the Qt Designer as included and the referenced tutorial makes it appear as part of WinPython as well....

Thanks!

**Comment by stonebig** [comment]
riverbanks, the maintainer/owner of PyQt5, stopped including the "Qt Designer" and  "Qt Linguist" in the PyQt5.6 wheels, after PyQt-5.5.
 
You have it in WinPython with Qt4, or in WinPython-64bit-3.4.4.3Qt5.exe because it's below Qt5.6.

For the time being:
- WinPython won't try to do better than what the official PyQt5 provider can do,
- in about a year, we may have the option to switch to PySide2 if it's finished and proved better on Windows (http://wiki.qt.io/PySide2)

**Comment by ngblume** [comment]
Hey stonebig,

thanks for the clarification....
Might be something to state on the frontpage of winpython, to be sure, that nobody expects all the components under "Overview" in the newest packages...

Cheers
Niels Göran

**Comment by MegaMinds1** [comment]
Error with qt.assistant.exe does not exist.Any help please
![error](https://user-images.githubusercontent.com/45468034/58661995-b4f63980-8318-11e9-8afd-3fe16b570796.PNG)
