### ISSUE TITLE
No interactive matplotlib graphics backend in WinPython 3.6.1.0

### ISSUE THREAD

**Issue by jondo** [winpython/winpython#532]
I am using Spyder, and I need interactive plot windows.
For the following tests, I have set the graphics backend to **Automatic** (in Preferences->Python console->External modules), then restarted Spyder to make sure this change is in effect.

In WinPython-64bit-3.6.1.0Qt5, I see the following:
```python
import matplotlib

matplotlib.get_backend()
Out[2]: 'module://ipykernel.pylab.backend_inline'
```
and plotting with matplotlib.pyplot does not open interactive windows.
The only other backend option is **None**, which of course also creates inline plots.

In WinPython-64bit-3.6.0.1Qt5, I correctly see
```python
Out[2]: 'TkAgg'
```
and plotting opens interactive windows with Tk's blue feather.

**Comment by hiccup7** [comment]
My experience suggests this type of problem is with Spyder.  See https://github.com/matplotlib/matplotlib/issues/7688
I suggest running code in in an IPython console instead of a Python console since this solution worked for me.  I had a problem with matplotlib blocking in the IPython console, but we found a work-around.  See https://github.com/spyder-ide/spyder/issues/4367

Spyder v3.14 is available as of today at http://www.lfd.uci.edu/~gohlke/pythonlibs/#spyder
If an IPython console in Spyder v3.14 doesn't work for you, I suggest reporting the problem to the Spyder team.

**Comment by jondo** [comment]
Ah, I was already using an IPython console, but I had changed the wrong preference!

I needed to switch Preferences->**IPython** console->Graphics->Backend from Inline to Automatic.
