### ISSUE TITLE
Crash with PyQt's QMessageBox and QDrag

### ISSUE THREAD

**Issue by JosselinKerdraon** [winpython/winpython#603]
Hi,

I've got few cases of crash in a my python application, originally developed with anaconda, but now using WinPython. 
I made a simple code to reproduce the problem:
 
```
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QMessageBox
import sys

class MainWindow(QMainWindow):

    def __init__(self):
        super(MainWindow, self).__init__()
        button = QPushButton("Push to open", self)
        button.clicked.connect(self._open_question)

    def _open_question(self):
        reponse = QMessageBox.question(self, "Big question",
                                       "Are you sure?",
                                       QMessageBox.Yes | QMessageBox.No | QMessageBox.Cancel)


appli = QApplication(sys.argv)
appli.setApplicationName("Test")

fenetre = MainWindow()
fenetre.show()
rslt = 1
try:
    rslt = appli.exec_()
except Exception as e:
    print(e)
    rslt = 888

```

It works with anaconda and with a native Python, but not with WinPython. 
Tha application crashes when QMessageBox::question is called. It takes 1 or 2 seconds to load and finished with "Python stopped working" dialog.
And I've got the same problem when calling QDrag.exec_()....

Am I doing something wrong or is there a problem ?

Regards

**Comment by stonebig** [comment]
if you execute from spyder, I would suggest "execute in a separate terminal"

**Comment by JosselinKerdraon** [comment]
I tried to run my application from Windows CMD and from PyCharm

**Comment by stonebig** [comment]
hum, it didn't blow up on me, but I launched it from Spyder.

If you don't move around you WinPython, try after having launched scripts\make_winpython_fix.bat

**Comment by hiccup7** [comment]
@JosselinKerdraon I suspect the reason for the bugs you are experiencing with WinPython is because of the very old version of WinPython you are using.  With Anaconda, updating to the latest version of all the included packages is automatic, while this is manual with WinPython.  But the latest version is not always a good thing.  Spyder, in particular, has had crashes for many months after years of stability.  Even the latest Spyder release (v3.2.8) has this bug that may affect you: https://github.com/spyder-ide/spyder/issues/6746

The simple solution for using WinPython is wait for 3.6.4.0Qt5 release.  If you don't want to wait for this release, try beta 4 from https://sourceforge.net/projects/winpython/files/WinPython_3.6/3.6.4.0/betas/
and upgrade Spyder manually from https://www.lfd.uci.edu/%7Egohlke/pythonlibs/
