### ISSUE TITLE
Issue starting Control Panel/Spyder on 3.7.4.0

### ISSUE THREAD

**Issue by tarun0094** [winpython/winpython#766]
Hi all
I am facing an issue with IDE launchers. I have the WinPython 3.7.4.0 release. After unpacking, the Spyder, Qt, Control Panel etc do not launch. I can run IDLE fine but spyder doesn't start. Is this a known issue or did I somehow botch the setting up?

**Comment by hiccup7** [comment]
WinPython 3.7.4.0 includes pyqt5 5.13.0, pyqtwebengine 5.13.0 and Spyder 3.3.5.  However, Spyder 3.3.5 requires pyqt5<5.13 and pyqtwebengine<5.13.  See https://github.com/spyder-ide/spyder/blob/3.x/setup.py
Also, WinPython Control Panel may not be fully tested with pyqt5 5.13.0.

I suggest downgrading pyqt5 and pyqtwebengine.  Use pip instead of WinPython Control Panel to do this.  If WinPython Control Panel then launches successfully, you may use it to upgrade Spyder to 3.3.6, as this fixed a couple of bugs.

Please report your results back here.

**Comment by stonebig** [comment]
@tarun0094 precise exactly which binary you downloaded,. Only Winpython64-3.7.4.0.exe and Winpython32-3.7.4.0.exe do include Spyder
