### ISSUE TITLE
what's the difference between 3.7.4.1.exe/3.7.4.1cod.exe/3.7.4.1ps2.exe ?

### ISSUE THREAD

**Issue by qq2898** [winpython/winpython#784]
where can i find notes about their difference?

**Comment by stonebig** [comment]
see package list ?
 - https://github.com/winpython/winpython/blob/master/changelogs/WinPython-64bit-3.7.4.1.md
 - https://github.com/winpython/winpython/blob/master/changelogs/WinPythoncod-64bit-3.7.4.1.md
 - https://github.com/winpython/winpython/blob/master/changelogs/WinPythonPs2-64bit-3.7.4.1.md


3.7.4.1 = with PyQt5
3.7.4.1cod = with vscode portable + python-vscode, but without Tensorflow nor PyTorch
3.7.4.1ps2 = with PySide2, so Spyder not working.

**Comment by qq2898** [comment]
thank you for your instant reply.



---Original---

**Comment by dearfad** [comment]
I want vscode, and Tensorflow/PyTorch, why not combine 3741 and 3741cod, for file size ?

**Comment by stonebig** [comment]
@dearfad yes. You can just copy the "/t/vscode" of the "cod" branch in the other ones (at the same relative place) , and your good to go.

with Tensorflow-2 and PyTorch-1.3 in the cod branch, it will be a 680 Mo download, not small,

**Comment by dearfad** [comment]
it really helps, thank you.

**Comment by Ivoz** [comment]
It would be very nice if the differences between the packages could be explained on the homepage. If someone new comes along to find a portable python to download, they are confronted with 8 different versions of WinPython to download and absolutely no information about which one they should click.

**Comment by stonebig** [comment]
@Ivoz you're right. This shall be improved a bit.

**Comment by stonebig** [comment]
would this be better ?
![image](https://user-images.githubusercontent.com/4312421/67616742-b3a03e80-f7dc-11e9-9dde-98f6f8fdf7e7.png)

**Comment by stonebig** [comment]
I hope you'll find the change a step in the right direction

千里之行，始於足下

**Comment by Ivoz** [comment]
I think having a legend box explaining the different versions would be a big help, e.g:

* (Default) = Comes with PyQt5 and Spyder IDE
* Ps2 = Same as default, but with PySide2 instead of PyQt5
* zero = minimal version, mostly just python
* Cod = Also includes an integrated VSCode IDE

Also, all the doubling of x86/x64 clutters things up. I would just have two links side by side, or do some javascript to switch between them (if you or someone in project likes frontend work). e.g 

WinPython 3.7.4.1 (Zero) -> [ ([32-bit](https://github.com/winpython/winpython/releases/download/2.1.20190928/Winpython32-3.7.4.1Zero.exe)), ([64-bit](https://github.com/winpython/winpython/releases/download/2.1.20190928/Winpython64-3.7.4.1Zero.exe)) ]

All the clutter from repeated text in general makes it a less friendly form. If "Python 3.7.4" is used in all 8 of the below downloads, no need to repeat that information 8 times!

Thanks for paying attention to a usability issue!
