### ISSUE TITLE
Spider does not start on a Win7 System because "api-ms-win-core-registry-l1-1-0.dll" missing

### ISSUE THREAD

**Issue by ventilator** [winpython/winpython#906]
I downloaded Winpython64-3.9.0.2cod.exe but Spyder.exe refuses to start because it complains "api-ms-win-core-registry-l1-1-0.dll" is missing.

I installed Windows6.1-KB2999226-x64.msu as well as VC_redist.x64.exe, this did not fix the problem.
Then I installed Spyder 4.2 native (Spyder_64bit_full.exe from Spyder's website), this version of Spyder starts. But the version within Winpython does not start.

OS: Win7 64bit

![image](https://user-images.githubusercontent.com/4276067/101931399-a52c0680-3bd9-11eb-8774-eda1082963a9.png)

**Comment by stonebig** [comment]
you have to download a much much older WinPython to get it working on Windows7.

**Comment by ArkadiuszMichalski** [comment]
Not necessarily, I use latest WinPython on Windows7, and it's works (at least in the python area). You need to manually download the file `api-ms-win-core-registry-l1-1-0.dll` and put it in `WinPython\python-3.9.0.amd64` or `WinPython\python-3.9.0.amd64\DLLs` (I don't remember exactly), or in `C:\Windows\System32`.

Installing ` Windows6.1-KB2999226-x64.msu` or `VC_redist.x64.exe` will not help here because for Win7 these packages do not contain the file `api-ms-win-core-registry-l1-1-0.dll`.

**Comment by stonebig** [comment]
so for Windows 7, last version that may still work is WinPython-3.8.9.0 of April 21th, 2021.
the older the better

**Comment by ventilator** [comment]
Thanks for the info.
Since Win7 is EOL in the meantime, I close this thread
